### ISSUE TITLE
Where can I find the listed modules required by the theme? 

### ISSUE THREAD

**Issue by gall0** [uclahs/surface#73]
Hi! Got some time to pull the theme repository into one of my projects. When I try to enable I get the following: 

Surface
A clean, accessible, and flexible Drupal front-end theme.
**This theme requires the listed modules to operate correctly.**

Please help.

**Comment by mariohernandez** [comment]
Hi, @gall0 sorry for the issue. We will update the README to be more clear.  To start, you will need the [components](https://www.drupal.org/project/components) module.

**Comment by mariohernandez** [comment]
Readme has been updated and this issue is now closed.
