### ISSUE TITLE
Buttons not behaving as expected 

### ISSUE THREAD

**Issue by gall0** [uclahs/surface#74]
Steps to reproduce:  

* Enabled **Surface** theme and set it as default. 
`Note that the administration theme is still set to the Adminimal theme; consequently, the theme on this page remains unchanged. All non-administrative sections of the site, however, will show the selected Surface theme by default. `

  Great!

* **Make Config Changes** 
`/admin/appearance/settings/surface`

  **Problem:** 
  After making configuration changes, when the Save configuration button is clicked, nothing happens. Tried switching to a different administration themes (mediteran & adminimal) and problem persists. 

* **Editing Content** 
  When viewing a page using **Surface** theme. 

  **Problem:** 
  Edit button does not work. 

No error messages on Drupal Logs or Browser Console.

**Comment by mariohernandez** [comment]
Closing ticket.
